kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry]
    config_path = "/etc/containerd/certs.d"
nodes:
- role: control-plane
  extraPortMappings:
  # Exposed API
  - containerPort: 30951
    hostPort: 8081
  # Exposed Dashboard
  - containerPort: 30952
    hostPort: 8082
  # Exposed RabbitMQ Port / Service
  - containerPort: 30953
    hostPort: 5672
  # Exposed Example Function Service
  - containerPort: 30950
    hostPort: 8080
  # - containerPort: 30952
  #   hostPort: 5000
