name: Go Tests and Docker Build

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  test-go:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21 # You can adjust the Go version as needed

    - name: Run Go Tests
      run: make test
    
  build:
    runs-on: ubuntu-lates

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Build Docker Image
        run: echo "Docker Build"

